carbon:
  bind: "127.0.0.0"
  port: 2003
  rollups:
    - 60s:5356800s
    - 900s:62208000s
  aggregatorDelay: 90
store:
  cluster:
    - "cassandra-1"
    - "cassandra-2"
  port: 9042
  keyspace: 'metric'
  maxConnections: 2048
  readTimeout: 10
  connectTimeout: 10
  maxRequests: 128
  batch: false
  batchSize: 500
  interval: 5
  pool: 10
index:
  name: "disthene"
  cluster:
    - "es-1"
    - "es-2"
  port: 9300
  index: "disthene"
  type: "path"
  bulk:
    actions: 10000
    interval: 5
stats:
  interval: 60
  tenant: "test"
  hostname: "disthene-1a"
  log: true